Fix wrong merge occurred when #130 was merged
SaturDJang/warp pull request #137
Opened 2017-05-14 06:32 UTC by getogrand

Fix wrong merge occurred when #130 was merged

2017-05-15 06:51 UTC, qkraudghgh requested changes
occur Error! but save is ok

I don't know why

I think there is an error in the line that I marked.

2017-05-15 06:51 UTC, qkraudghgh commented on warp/static/js/create/index.js
> +    document.getElementById('id_markdown').value = editor.getValue();
I think this line is error

I don't know why

editor id is `markdown_editor`, not `id_markdown`

2017-05-15 13:58 UTC, getogrand commented on warp/static/js/create/index.js
> +    document.getElementById('id_markdown').value = editor.getValue();
@qkraudghgh It was explained in the Slack. Please re-review! 😄

2017-05-16 04:23 UTC, kyunooh approved these changes

2017-05-16 04:25 UTC, qkraudghgh approved these changes

2017-05-16 04:25 UTC, kyunooh approved these changes

2017-05-16 04:26 UTC, merged