Write Presentation list test
SaturDJang/warp pull request #43
Opened 2016-11-26 03:04 UTC by hyunji92

2016-12-03 02:41 UTC, mingrammer requested changes

2016-12-03 02:41 UTC, mingrammer commented on presentation/tests.py
> +        name = "Name name"
Using the random values would be better.

2016-12-03 02:41 UTC, mingrammer commented on presentation/tests.py
> +        for _ in (0, 20):
What is intend of it?

2016-12-03 02:41 UTC, mingrammer commented on presentation/tests.py
> +        self.presentation = Presentation(subject="subject",
Using the random values would be better.

2016-12-03 10:50 UTC, qkraudghgh commented on presentation/tests.py
> +        name = "Name name"
+1

2016-12-10 02:44 UTC, kyunooh commented on presentation/tests.py
> +        self.presentation = Presentation(subject="subject",
Sometimes.. random is dangerous on test case. cause when test is broken, we can't check what is wrong.

2016-12-10 02:53 UTC, kyunooh commented on presentation/tests.py
> +        for _ in (0, 20):
fixit!

2016-12-10 03:06 UTC, mingrammer commented on presentation/tests.py
> +        self.presentation = Presentation(subject="subject",
Our Presentation model has no limitation except length. It means that the model should accept any values with any length less than limit length. So, if testcase is failed with random values, the view may have some problems.

And, if something is wrong, you can use debug tools. Random values would not be problems.

2016-12-10 03:08 UTC, mingrammer commented on presentation/tests.py
> +        self.presentation = Presentation(subject="subject",
Testcase could be dangerous with single concrete values rather than randoms in this case i think.

2016-12-10 05:08 UTC, mingrammer requested changes

2016-12-10 05:08 UTC, mingrammer commented on presentation/tests.py
> +        self.assertContains(response, self.presentation.subject)
It is so weak. The list page already has 'subject' text, so this assertion wiil be always passed with if `subject` value is 'subject'. So you should use random values. `markdown` and `html` are weak too. 

Please use random value for testing.

2016-12-10 05:11 UTC, mingrammer commented
Why don't you use random values? for debugging? You can just use debugging tools for that. random would not be problems for finding the wrong somethings. 

I don't understand that using the concrete single value.

2016-12-10 05:13 UTC, mingrammer commented
If you want to use concrete values, you should use testcases more thant one. Random value of course also not perfect, But, just one concrete value is so weak for testing.

2016-12-10 05:21 UTC, mingrammer commented on presentation/tests.py
> +        self.assertContains(response, self.presentation.subject)
Or use the context value of response to assert equality with `self.presentation.subject` exactly.

2016-12-10 05:32 UTC, getogrand commented
@mingrammer I don't agree with your opinion about random-value-testing.
Using random value for testcase is usually considered as an antipattern.
Assume that your testcase is randomly success and randomly fail. It means the test code being another debugging hell. 
The most important meaning of making testcase is making debug easy. But random-asserts makes hard to debug.
See other's testcode. See the junit's testcode, see the django's testcode and see the golang's testcode. They don't use random values for testing.
If we have to use random values for simple response-assert-testing, testcodes of many famous webframework must use random value but they don't.
If we start using random value for simple response-assert-testing, then we have to use random assert on 80% of our test methods, which shadow the "really important part" and "truly business logic".
Would you mind reconsidering to use random-assert after you read other super-geek's test codes?

2016-12-10 05:56 UTC, mingrammer commented
@getogrand So, how do you choose proper testcases? In above, the `subject='subject'` is not proper because the list page already has 'subject' text. So although if the return of `list` view has no `subject` value , the test will be passed.

2016-12-10 06:32 UTC, mingrammer commented
@getogrand I agree with part of your opinion. The random values could not be reproduced, so, debugging being hard. Ok I got it. This is really important.

But, I don't know methodologies for choosing the proper testcases. Could you teach about that to me?

2016-12-10 06:50 UTC, getogrand commented
If I have written this testcase, I would just use different 'expectation string' for subject field. For example, `subject='This is subject'` instead of `subject='subject'`.
[See this testcode of django framework itself. We can get the hint for writing tests from this.](https://github.com/django/django/blob/f095b249baf34bbdd4c0b28c9bde05b4d20681be/tests/template_tests/test_response.py).

2016-12-10 07:08 UTC, mingrammer commented
@getogrand Well .. that is good. So, other values for testing should be changed. (`username='username'` and others not proper) 

And `assertEqual(response.context['<context data key>'], expected value)` is better I think. It can check the value exactly. `assertContains` is weak sometimes.

2016-12-10 07:14 UTC, getogrand submitted a review, later dismissed

2016-12-10 07:14 UTC, getogrand commented on presentation/tests.py
> +        self.assertContains(response, self.presentation.subject)
I don't agree using random value, but I agree @mingrammer 's opinion that `subject="subject"` is not a proper test data. 
How about change the test data more 'real-like'. Imagine some use case on production. For example,
```python
self.presentation = Presentation(subject="I love you, mother!", 
    author=self.test_user, 
    markdown=~~~~~~blabla~~~~~~, 
    html=~~~~blabla~~~~)
```
Of course, It makes test code verbose. But there is solution on Django. [The fixture](https://docs.djangoproject.com/en/1.10/topics/testing/tools/#fixture-loading).

2016-12-10 07:28 UTC, getogrand commented
@mingrammer I think it depends on case. If we just want to check context value of django request, `assertEqual(response.context['<context data key>'], expected value)` is the answer. However if you want to check HTTP response or HTML data, `assertContains` is needed.
There is big different between two ways above on application layering(abstraction layer?) perspective.
Former one is about python variable layer, latter one is about client(browser) layer.
Imagine that someone made his controller(view on django) well, but made lots of mistake on template. Latter will fail although former will success.

2016-12-10 07:50 UTC, mingrammer commented
@getogrand The case of HTTP response also needs to use `assertEqual()` sometimes (e.g. check the value of `form` are rendered on template). But In our case, if the `subject` value is like "This is subject", I'm ok for using `assertContains`.

And we needs to check the status code.

2016-12-10 07:51 UTC, mingrammer commented on presentation/tests.py
> +
We need to check the status code. `assertEqual(response.status_code, 200)`

2016-12-11 04:15 UTC, kyunooh commented
HaHa... There is so many conversations...
Sorry, I just want to create minimum successful test, cause some reasons.
First, there is no test case. It means we don't know we can make worked test or not.
Second, I attend minimum working code when I start working. and I develop more and more. It is product code or test code.
Third, teaching how to make test code on django. 

I will apply your opinion on code and I will commit. Thank you.

2016-12-17 03:01 UTC, mingrammer requested changes

2016-12-17 03:01 UTC, mingrammer commented on presentation/tests.py
> +    def test_get_presentation_list_page(self):
You should assert the list length (maybe 20)

2016-12-27 17:19 UTC, kyunooh commented
I checked about fixture that is old way now. That is not recommending now on communities. (and twoscoop either.)
I will create dummy data by factory boy, creating dummy data library.

2016-12-28 11:25 UTC, getogrand commented
@kyunooh Great! I am happy to know a much more nice way.
P.S. The factory-boy is influenced by factory-girl which is a ruby❤️ library!

2017-01-07 07:49 UTC, kyunooh commented
Please review and merge :D

2017-01-07 07:54 UTC, qkraudghgh commented on compose/django/Dockerfile-dev
> -RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
THX for remove apt-get script

2017-01-07 08:59 UTC, mingrammer approved these changes

2017-01-07 08:59 UTC, merged