Add usage sidebar feature.
SaturDJang/warp pull request #59
Opened 2016-12-10 13:16 UTC by getogrand

This fixes #25

2016-12-10 13:26 UTC, qkraudghgh approved these changes
I think we fixed indent rules.
I want `Python 4 size`, `Javascript 2 size`, `HTML 2 size`
If you agree, please edit it.
And read the other comments.
Thanks

2016-12-10 13:26 UTC, qkraudghgh commented on warp/static/js/create.js
> +  $('.usage-toggle-btn').click(function (e) {
Can you translate it into es6 grammar?
Or do I commit?

2016-12-10 13:26 UTC, qkraudghgh commented on warp/static/sass/mobile/presentation.create.scss
> +  @media (max-width: 1585px) {
If it's the code that only Desktop uses
It would be nice if you could create one more file in desktop and rewrite it

2016-12-10 13:33 UTC, qkraudghgh requested changes
sorry, Approve is my mistake

2016-12-10 13:33 UTC, getogrand commented on warp/static/sass/mobile/presentation.create.scss
> +  @media (max-width: 1585px) {
Actually, this code only targets screens bigger than 1584px.
It isn't used to distinguish if the client is desktop.
It is used to distinguish if the client has minimum width to display usage sidebar.
On the other words, we won't support 1583px desktop client.

2016-12-10 13:38 UTC, qkraudghgh commented on warp/static/sass/mobile/presentation.create.scss
> +  @media (max-width: 1585px) {
I don't know how big the 1583px is.
but, I understand it. thx.

2016-12-10 13:45 UTC, getogrand commented
I fixed indent and applied es6 syntax!

2016-12-10 13:47 UTC, qkraudghgh commented
thx, nice work
but can I participate in this issue?
I want fix javascipt code for perfectly converting es6

2016-12-10 13:50 UTC, getogrand commented
There was some missing indent, sorry.
And, your welcome for fix our code of course!

2016-12-10 14:04 UTC, qkraudghgh commented
Just few modification.

And I want know two things.

1. Why did you name it usage-sidebar instead issue-[number]? 
Is there any strategy I don't know?

2. My 13 inches mac air does not see Usage-sidebar, We don't support this monitor size?

2016-12-11 09:06 UTC, getogrand commented
@qkraudghgh 
1. This branch name is a legacy thing. We named it before we define our branch naming rule. Please accept this branch name just this once.
2. The 13' Macbook Air has 1440px width. If we want to display usage sidebar for this device, we have to discuss about layout. It's hard to explain this text comment, so how about talk this on next meeting?

2016-12-11 09:41 UTC, mingrammer commented
I think we should support usage sidebar for 13' MBA too. And need to option button to hide the sidebar like gitbook

2016-12-11 09:48 UTC, getogrand commented
@mingrammer We already have show/hide toggle button! :smiley:

2016-12-11 09:56 UTC, mingrammer commented
Good

2017-01-07 07:15 UTC, qkraudghgh commented
@getogrand 
I rebase this branch from master and forced push.

And I don't understand one thing that Why reason `Show Usage Button` disappear some monitor sizes

2017-01-07 08:53 UTC, getogrand commented
As I said above comments, there is no available width on screen has width smaller than 1584px.
We can change UI design to enable usage sidebar on small screen after we discuss about it! 😄

2017-01-07 08:57 UTC, qkraudghgh approved these changes

2017-01-07 08:57 UTC, qkraudghgh commented
OK, I'll approve once. you check and merge this.

2017-01-07 11:50 UTC, getogrand commented
Thanks for approving.

2017-01-07 11:50 UTC, merged