Replace django-compressor with gulp and its watch
SaturDJang/warp pull request #75
Opened 2017-01-05 14:52 UTC by getogrand

1. Remove django-compressor and its dependencies.
2. Enable automatic building of scss and es6 using gulp.
    1. This improves es6 build performance significantly.
3. Support sourcemap feature to css and javascript.
4. Use node-sass instead of ruby sass.
5. Support [browsersync](https://www.browsersync.io/) feature with [3000 port](http://localhost:3000).
    1. If you modify scss or js file, the browser will be refreshed automatically.
    2. If you don't want use this feature, just use [8000 port](http://localhost:8000).
    3. There is web app for managing browsersync on [3001 port](http://localhost:3001).
6. Docker-related file was changed for supporting gulp watch automatically.
    1. To run server, just type `docker-compose up`(add `--build` option flag at the first time.)
    2. We use `npm start` command internally in docker for starting django server and gulp watch task.

2017-01-06 06:43 UTC, qkraudghgh requested changes
Good work!
But I suggest you this folder structure
because Need to separate build files to working directory
```dist    
│
└───map
│   └───js
│       │   file111.js.map
│       │   file112.js.map
│   └───css
│       │   file111.css.map
│       │   file112.css.map
│   
└───js
    │   file021.js
    │   file022.js
└───css
    │   file021.css
    │   file022.css
```

and you just transpile only one file (`main.scss`)
but watch task watching all `*.scss` files

----

This PR nice work in my local computer but doesn't work on docker

plz check this

2017-01-07 04:55 UTC, qkraudghgh approved these changes

2017-01-07 04:56 UTC, myungseokang approved these changes

2017-01-07 05:00 UTC, qkraudghgh commented
REF
#74 
#70

2017-01-07 05:03 UTC, kyunooh approved these changes

2017-01-07 05:03 UTC, merged